[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  REACT_APP_USE_PROXY_API = "true"
  REACT_APP_USE_REAL_TRACKSHIP_API = "true" 